### ISSUE TITLE
Issue fetching tagesanzeiger.ch

### ISSUE THREAD

**Issue by JanJastrow** [fivefilters/ftr-site-config#441]
Hi guys,

I have trouble fetching the content of articles from tagesanzeicher.ch
They got a loading-page in front of the content and I don't know how to get around it.

Test-URL:
https://m.tagesanzeiger.ch/articles/13916862
Siteconfig:
http://siteconfig.fivefilters.org/grab.php?url=https%3A%2F%2Fm.tagesanzeiger.ch%2Farticles%2F13916862

**Comment by HolgerAusB** [comment]
@JanJastrow did you get arround your problem or still interested in? Your issue is four years old...
It seems that links with subdomain m. doesn't work (anymore).

A fast check with https://tagesanzeiger.ch/articles/13916862 on FTR shows the complete article.  Although there is some ugly fringe in the article. Maybe I will look into this in a few days.

**Comment by HolgerAusB** [comment]
@JanJastrow: JUst updates the site-config, waiting for approval by maintainers.

 If you host FTR on your own machine. You should try to extract the cookies from your Browser while logged in to tagesanzeiger and try to identify the cookie. Then copy the file tagesanzeiger.ch.txt from site_config/standard to site_config/custom an there you add a line like this:
`http_header(cookie): cookiename=cookiecontent`

No guarantee that this will work
