### ISSUE TITLE
Provide guidance on file naming

### ISSUE THREAD

**Issue by burkemw3** [fivefilters/ftr-site-config#670]
Will someone please provide guidance on file naming?

I keep opening files as `.example.com.txt`. Primarily because most of the first listed files have that naming scheme. A few of my PRs have their file names adjusted, but I don’t fully understand why. 

Adding something to the readme’s contributing section would be helpful, at least for me, if you maintainers don’t want to keep adjusting file names.

**Comment by j0k3r** [comment]
`.example.com.txt` wil work for any subdomain of `example.com`: `video.example.com`, `news.example.com`, `www.example.com`, `m.example.com`, etc.

`www.example.com.txt` will only work for `www.example.com`.

In fact, it's not a problem to add `.example.com.txt` instead of `www.example.com.txt` it's just less accurate.

I fixed one of your added file yesterday but missed other one.

**Comment by fivefilters** [comment]
The confusion might be around the way this is handled in Full-Text RSS. In the past I've edited pull requests where, e.g. `.example.com.txt` was targeting `www.example.com` (in `test_url`) because in Full-Text RSS this won't match `www.example.com`. I wonder if that's what's confused @burkemw3. The `www` subdomain is treated as a special case so `example.com.txt` is needed to match `www.example.com` and `example.com`. `.example.com.txt` will match everything else except the above two.

This also creates a problem when a site has essentially the same layout under `example.com` and all its subdomains. We can't use one file to target the site, we have to duplicate the contents of `example.com.txt` in `.example.com.txt`.

This isn't very intuitive, and I've realised that most people assume `.example.com.txt` will match all variations (`example.com`, `www.example.com`, `news.example.com`, etc.).

@j0k3r if I'm understanding correctly in your case (Graby/Wallabag) the difference with what I've described is that `.example.com.txt` will match `www.example.com`. Is that right?

**Comment by j0k3r** [comment]
@fivefilters I think I made a confusion by replying too fast. I use the same behavior as in Full-Text RSS (not what I said in my _minimized_ comment)

**Comment by fivefilters** [comment]
Thanks @j0k3r. In that case, until the situation improves, we can summarise the file naming advice as:

Use `example.com.txt` for

* www.example.com
* example.com

Use `.example.com.txt` for

* sport.example.com
* news.example.com
* environment.example.com
* etc.

Use `sport.example.com.txt` target just that sub-domain:

* sport.example.com

Note: `.example.com.txt` will _not_ match `www.example.com` or `example.com`

I've now added this to the [Readme](https://github.com/fivefilters/ftr-site-config/blob/master/README.md#file-naming)
